##
## MIT License
##
## Copyright (c) 2020-2021 NVIDIA CORPORATION.
##
## Permission is hereby granted, free of charge, to any person obtaining a
## copy of this software and associated documentation files (the "Software"),
## to deal in the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
## DEALINGS IN THE SOFTWARE.##

# @package _global_
use_cuda: True
cuda_device_num: 0


sim_params:
  sim_urdf: "urdf/franka_description/franka_panda_no_gripper.urdf"
  robot_pose: [0, 1.0, 0, 0.0, -0.707107, -0.707107, 0.0]
  init_state: [-0.01779206, -0.76012354,  0.01978261, -2.34205014,  0.02984053, 1.54119353,  0.75344866] # coresponds to npinet
  control_mode: 'torque'

  asset_options:
    fix_base_link: True
    flip_visual_attachments: True
    armature: 0.001
    disable_gravity: True
    collapse_fixed_joints: True
  camera:
    label_map: {'robot':2, 'ground':0}

